### ISSUE TITLE
SR todo after review meeting

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#143]
- [x] add full surveys names in Table 1 if fit; if not, reference new Fig 1 caption.
- [x] TODO-Month TODO-Day, 2022 Change to today
- [x] add IPHC to Fig 1? No, but note in caption and ref fig 4
- [x] add abbreviations to caption in Fig 1
- [x] Approver Name - Andrew Thomson... March 30
- [x] automated -> reproducible
- [x] short title: Groundfish Data Update 2021
- [x] Add Tope shark COSEWIC report

IPHC stuff:
- [x] gfiphc - 2021 empty = 0 do in code!?  Do in synopsis code if possible.
- [x] make NAs 0s for IPHC  - should get fixed by the above point. BUT keep as NA's if the full time series is NA's (i.e. we don't want to show a time series of 0's if that species was never caught, we want the blank plot).
- [x] thought about making first 3 years for skates NAs, but it's not that simple. Andy will add text as per next bullet, as not all species started getting enumerated at the same time. Think there's similar issues maybe with grenadiers, so will put a general statement in and use skates as an example).
- [x] Or, just add to IPHC description/caveats

Later:
- [ ] ISBN ISBN-Here Cat No. Cat-Number-Here
- [ ] 2022/999.
- [ ] Email about pre-pub version

**Comment by andrew-edwards** [comment]
Thanks Philina, I was going to look at these today or tomorrow. I can do third and fourth IPHC ones - I think Sean will have to do the first IPHC one in gfsynopsis code.

**Comment by andrew-edwards** [comment]
The above commit describes the changes for the IPHC NA's, but I haven't done the actual code changes as can't as they're better done in gfsynopsis not gfiphc. See the two non-checked boxes above for what to do.

**Comment by ecophilina** [comment]
What if any 0's prior to any positive values in IPHC for skates and grenadiers were made NA, at least up to a cutoff at which point we were confident that 0's could be considered true 0s?

**Comment by andrew-edwards** [comment]
Good idea, which I think would be the ideal answer. 
But the same thing would need to be done for some other species also, and for some the early 0's could be true 0's (i.e. they were identifying them). This could be looked into but would be tedious (and for rare species the time series isn't really going to be used anyway).
